In [1]:
import pandas as pd

from dbnomics import fetch_series

import warnings
warnings.filterwarnings("ignore", category=FutureWarning)

In [2]:
indicators = ["NY.GDP.MKTP.CN",'FM.LBL.MONY.CN','FM.LBL.MQMY.CN','GC.REV.TAX.GD.CN','GC.REV.TOTL.GD.ZS','GC.REV.TOTL.GD.CN','GC.XPN.TOTL.GD.ZS','GC.XPN.TOTL.GD.CN','GC.BAL.CASH.GD.ZS','GC.BAL.CASH.GD.CN','SL.TLF.15UP.UEM','LM.POP.EPP.TOT']

In [3]:
df = fetch_series("AFDB", "bbkawjf", dimensions={"indicator": indicators}, max_nb_series=1000000)
df = df.reset_index(drop=True)
df.head(20)

,@frequency,provider_code,dataset_code,dataset_name,series_code,series_name,original_period,period,original_value,value,country,indicator,units,scale,frequency,Country,Indicator,Units,Scale,Frequency
0,annual,AFDB,bbkawjf,AFDB Socio Economic Database,FM.LBL.MONY.CN.AGO,Money (current LCU) - Angola,1995,1995-01-01,2689020.0,2.689020e+06,AGO,FM.LBL.MONY.CN,current-lcu,1,A,Angola,Money (current LCU),current LCU,1,Annual
1,annual,AFDB,bbkawjf,AFDB Socio Economic Database,FM.LBL.MONY.CN.AGO,Money (current LCU) - Angola,1996,1996-01-01,93917900.0,9.391790e+07,AGO,FM.LBL.MONY.CN,current-lcu,1,A,Angola,Money (current LCU),current LCU,1,Annual
2,annual,AFDB,bbkawjf,AFDB Socio Economic Database,FM.LBL.MONY.CN.AGO,Money (current LCU) - Angola,1997,1997-01-01,194910000.0,1.949100e+08,AGO,FM.LBL.MONY.CN,current-lcu,1,A,Angola,Money (current LCU),current LCU,1,Annual
3,annual,AFDB,bbkawjf,AFDB Socio Economic Database,FM.LBL.MONY.CN.AGO,Money (current LCU) - Angola,1998,1998-01-01,272432000.0,2.724320e+08,AGO,FM.LBL.MONY.CN,current-lcu,1,A,Angola,Money (current LCU),current LCU,1,Annual
4,annual,AFDB,bbkawjf,AFDB Socio Economic Database,FM.LBL.MONY.CN.AGO,Money (current LCU) - Angola,1999,1999-01-01,1206550000.0,1.206550e+09,AGO,FM.LBL.MONY.CN,current-lcu,1,A,Angola,Money (current LCU),current LCU,1,Annual
5,annual,AFDB,bbkawjf,AFDB Socio Economic Database,FM.LBL.MONY.CN.AGO,Money (current LCU) - Angola,2000,2000-01-01,15840411639.280001,1.584041e+10,AGO,FM.LBL.MONY.CN,current-lcu,1,A,Angola,Money (current LCU),current LCU,1,Annual
6,annual,AFDB,bbkawjf,AFDB Socio Economic Database,FM.LBL.MONY.CN.AGO,Money (current LCU) - Angola,2001,2001-01-01,41660774283.559898,4.166077e+10,AGO,FM.LBL.MONY.CN,current-lcu,1,A,Angola,Money (current LCU),current LCU,1,Annual
7,annual,AFDB,bbkawjf,AFDB Socio Economic Database,FM.LBL.MONY.CN.AGO,Money (current LCU) - Angola,2002,2002-01-01,106793512283.316986,1.067935e+11,AGO,FM.LBL.MONY.CN,current-lcu,1,A,Angola,Money (current LCU),current LCU,1,Annual
8,annual,AFDB,bbkawjf,AFDB Socio Economic Database,FM.LBL.MONY.CN.AGO,Money (current LCU) - Angola,2003,2003-01-01,179518093989.351013,1.795181e+11,AGO,FM.LBL.MONY.CN,current-lcu,1,A,Angola,Money (current LCU),current LCU,1,Annual
9,annual,AFDB,bbkawjf,AFDB Socio Economic Database,FM.LBL.MONY.CN.AGO,Money (current LCU) - Angola,2004,2004-01-01,266677656751.022003,2.666777e+11,AGO,FM.LBL.MONY.CN,current-lcu,1,A,Angola,Money (current LCU),current LCU,1,Annual
10,annual,AFDB,bbkawjf,AFDB Socio Economic Database,FM.LBL.MONY.CN.AGO,Money (current LCU) - Angola,2005,2005-01-01,428566980082.890015,4.285670e+11,AGO,FM.LBL.MONY.CN,current-lcu,1,A,Angola,Money (current LCU),current LCU,1,Annual
11,annual,AFDB,bbkawjf,AFDB Socio Economic Database,FM.LBL.MONY.CN.AGO,Money (current LCU) - Angola,2006,2006-01-01,685068282991.180054,6.850683e+11,AGO,FM.LBL.MONY.CN,current-lcu,1,A,Angola,Money (current LCU),current LCU,1,Annual
12,annual,AFDB,bbkawjf,AFDB Socio Economic Database,FM.LBL.MONY.CN.AGO,Money (current LCU) - Angola,2007,2007-01-01,1023638868705.589966,1.023639e+12,AGO,FM.LBL.MONY.CN,current-lcu,1,A,Angola,Money (current LCU),current LCU,1,Annual
13,annual,AFDB,bbkawjf,AFDB Socio Economic Database,FM.LBL.MONY.CN.AGO,Money (current LCU) - Angola,2008,2008-01-01,2094018359082.639893,2.094018e+12,AGO,FM.LBL.MONY.CN,current-lcu,1,A,Angola,Money (current LCU),current LCU,1,Annual
14,annual,AFDB,bbkawjf,AFDB Socio Economic Database,FM.LBL.MONY.CN.AGO,Money (current LCU) - Angola,2009,2009-01-01,2543723059447.950195,2.543723e+12,AGO,FM.LBL.MONY.CN,current-lcu,1,A,Angola,Money (current LCU),current LCU,1,Annual
15,annual,AFDB,bbkawjf,AFDB Socio Economic Database,FM.LBL.MONY.CN.AGO,Money (current LCU) - Angola,2010,2010-01-01,2678230070993.430176,2.678230e+12,AGO,FM.LBL.MONY.CN,current-lcu,1,A,Angola,Money (current LCU),current LCU,1,Annual
16,annual,AFDB,bbkawjf,AFDB Socio Economic Database,FM.LBL.MONY.CN.AGO,Money (current LCU) - Angola,2011,2011-01-01,3673111017825.330078,3.673111e+12,AGO,FM.LBL.MONY.CN,current-lcu,1,A,Angola,Money (current LCU),current LCU,1,Annual
17,annual,AFDB,bbkawjf,AFDB Socio Economic Database,FM.LBL.MONY.CN.AGO,Money (current LCU) - Angola,2012,2012-01-01,3853026880550.060059,3.853027e+12,AGO,FM.LBL.MONY.CN,current-lcu,1,A,Angola,Money (current LCU),current LCU,1,Annual
18,annual,AFDB,bbkawjf,AFDB Socio Economic Database,FM.LBL.MONY.CN.AGO,Money (current LCU) - Angola,2013,2013-01-01,4398099013490.820312,4.398099e+12,AGO,FM.LBL.MONY.CN,current-lcu,1,A,Angola,Money (current LCU),current LCU,1,Annual
19,annual,AFDB,bbkawjf,AFDB Socio Economic Database,FM.LBL.MONY.CN.AGO,Money (current LCU) - Angola,2014,2014-01-01,5110115937912.120117,5.110116e+12,AGO,FM.LBL.MONY.CN,current-lcu,1,A,Angola,Money (current LCU),current LCU,1,Annual

In [5]:
df.to_excel('AFDB.xlsx')

In [6]:
df.to_pickle("AFDB.pkl")

In [7]:
df1 = pd.read_pickle("AFDB.pkl")
df1.equals(df)

True