In [1]:
from fredapi import Fred

fred = Fred(api_key="58cae177d1497e9f11d5b83454e91a90")

In [2]:
series_ids = {
    'nGDP_LCU': 'GDPA',
    'rGDP_LCU': 'GDPCA',
    'rGDP_LCU_pc': 'A939RX0Q048SBEA',
    'infl': 'FPCPITOTLZGUSA',
    'pop': 'B230RC0A052NBEA',
    'sav': 'A929RC1A027NBEA',
    'govtax': 'W006RC1Q027SBEA',
    'govexp': 'W068RCQ027SBEA',
    'exports': 'EXPGSA',
    'imports': 'IMPGSA',
    'CA': 'A124RC1A027NBEA',
    'govdebt_GDP': 'GFDEGDQ188S',
    'cbrate': 'RIFSPFFNA',
    'govdef_GDP': 'FYFSGDA188S',
    'govrev': 'AFRECPT',
    'M0': 'BOGMBASE',
    'M1': 'M1SL',
    'M2': 'M2SL',
    'unemp': 'UNRATE',
    'HPI': 'USSTHPI',
    'ltrate': 'BOGZ1FL073161113Q',
    'strate': 'RIFSGFSM03NA'
}

In [3]:
import pandas as pd

data = {}
for name, series_id in series_ids.items():
    data[name] = fred.get_series(series_id)

df = pd.DataFrame(data)
df.head(20)

,nGDP_LCU,rGDP_LCU,rGDP_LCU_pc,infl,pop,sav,govtax,govexp,exports,imports,...,cbrate,govdef_GDP,govrev,M0,M1,M2,unemp,HPI,ltrate,strate
1929-01-01,104.556,1191.124,NaN,NaN,121878.0,20.113,NaN,NaN,5.939,5.556,...,NaN,0.70202,3.694,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1930-01-01,92.160,1089.785,NaN,NaN,123188.0,15.821,NaN,NaN,4.444,4.121,...,NaN,0.80078,2.936,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1931-01-01,77.391,1019.977,NaN,NaN,124149.0,9.097,NaN,NaN,2.906,2.905,...,NaN,-0.59697,1.939,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1932-01-01,59.522,888.414,NaN,NaN,124949.0,3.977,NaN,NaN,1.975,1.932,...,NaN,-4.59494,1.624,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1933-01-01,57.154,877.431,NaN,NaN,125690.0,3.940,NaN,NaN,1.987,1.929,...,NaN,-4.55261,2.550,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1934-01-01,66.800,972.263,NaN,NaN,126485.0,7.026,NaN,NaN,2.561,2.239,...,NaN,-5.36826,3.362,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1935-01-01,74.241,1058.836,NaN,NaN,127362.0,10.399,NaN,NaN,2.769,2.982,...,NaN,-3.77554,3.667,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1936-01-01,84.830,1195.251,NaN,NaN,128181.0,12.348,NaN,NaN,3.007,3.154,...,NaN,-5.07368,4.601,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1937-01-01,93.003,1256.503,NaN,NaN,128961.0,17.127,NaN,NaN,4.039,3.961,...,NaN,-2.35799,6.582,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1938-01-01,87.352,1214.869,NaN,NaN,129969.0,12.719,NaN,NaN,3.811,2.845,...,NaN,-0.10189,6.019,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1939-01-01,93.437,1312.365,NaN,NaN,131028.0,14.558,NaN,NaN,3.969,3.136,...,NaN,-3.04590,6.272,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1940-01-01,102.899,1428.075,NaN,NaN,132122.0,19.492,NaN,NaN,4.897,3.426,...,NaN,-2.83773,8.211,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1941-01-01,129.309,1681.049,NaN,NaN,133402.0,31.130,NaN,NaN,5.482,4.449,...,NaN,-3.82108,14.910,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1942-01-01,165.952,1998.542,NaN,NaN,134860.0,41.602,NaN,NaN,4.375,4.627,...,NaN,-12.35478,22.271,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1943-01-01,203.084,2338.761,NaN,NaN,136739.0,47.013,NaN,NaN,4.034,6.280,...,NaN,-26.86278,38.473,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1944-01-01,224.447,2524.752,NaN,NaN,138397.0,42.830,NaN,NaN,4.880,6.904,...,NaN,-21.18852,40.067,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1945-01-01,228.007,2500.057,NaN,NaN,139928.0,32.556,NaN,NaN,6.781,7.547,...,NaN,-20.85594,41.529,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1946-01-01,227.535,2209.911,NaN,NaN,141389.0,41.521,NaN,NaN,14.156,6.974,...,NaN,-7.00376,39.452,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1947-01-01,249.616,2184.614,15248.0,NaN,144126.0,49.244,36.860,NaN,18.740,7.933,...,NaN,1.60967,42.814,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1947-04-01,NaN,NaN,15139.0,NaN,NaN,NaN,36.316,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.to_excel('FRED.xlsx')

In [5]:
df.to_pickle('FRED.pkl')

In [6]:
df1=pd.read_pickle('FRED.pkl')
df1.equals(df)

True