In [1]:
import pandas as pd

from dbnomics import fetch_series, fetch_series_by_api_link

In [2]:
df = fetch_series("SARB", "QB", dimensions={"topic": ['MB','NA','PF','FM'], 'freq':['A']}, max_nb_series=1000000)
df.reset_index(inplace=True, drop=True)
df.head()

,@frequency,provider_code,dataset_code,dataset_name,series_code,series_name,original_period,period,original_value,value,topic,unit,freq,Topic,Unit,Frequency
0,annual,SARB,QB,Quarterly Bulletin,KBP1000J,South African Reserve Bank liabilities: Notes ...,1960,1960-01-01,255.0,255.0,MB,RMILL,A,Money and Banking,RMILL,Annual
1,annual,SARB,QB,Quarterly Bulletin,KBP1000J,South African Reserve Bank liabilities: Notes ...,1961,1961-01-01,276.0,276.0,MB,RMILL,A,Money and Banking,RMILL,Annual
2,annual,SARB,QB,Quarterly Bulletin,KBP1000J,South African Reserve Bank liabilities: Notes ...,1962,1962-01-01,302.0,302.0,MB,RMILL,A,Money and Banking,RMILL,Annual
3,annual,SARB,QB,Quarterly Bulletin,KBP1000J,South African Reserve Bank liabilities: Notes ...,1963,1963-01-01,337.0,337.0,MB,RMILL,A,Money and Banking,RMILL,Annual
4,annual,SARB,QB,Quarterly Bulletin,KBP1000J,South African Reserve Bank liabilities: Notes ...,1964,1964-01-01,355.0,355.0,MB,RMILL,A,Money and Banking,RMILL,Annual

In [3]:
df.to_csv('ZAF_1.csv')

In [4]:
df.to_pickle('ZAF_1.pickle')

In [5]:
df1 = pd.read_pickle('ZAF_1.pickle')
df1.equals(df)

True